name: Mega-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
jobs:
  build:
    name: Mega-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Mega-Linter
        uses: oxsecurity/megalinter@v7
        env:
          ENABLE_LINTERS: PYTHON_PYRIGHT
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}